
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

const getAIClient = (apiKey?: string) => {
  return new GoogleGenAI({ apiKey: apiKey || process.env.API_KEY || '' });
};

/**
 * Analyzes the user's current photo to identify what they are wearing.
 */
export const analyzeOutfit = async (base64Image: string): Promise<string> => {
  const ai = getAIClient();
  const data = base64Image.split(',')[1];
  
  const response: GenerateContentResponse = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: {
      parts: [
        {
          inlineData: {
            mimeType: 'image/png',
            data: data,
          },
        },
        {
          text: "Describe exactly what this person is wearing in one short sentence. Focus only on clothing items and colors."
        }
      ]
    }
  });

  return response.text || "clothing";
};

/**
 * Transforms the outfit using Gemini 2.5 Flash Image.
 */
export const transformOutfit = async (
  base64Image: string,
  stylePrompt: string,
  currentOutfitDesc: string,
  blurBackground: boolean = false
): Promise<string> => {
  const ai = getAIClient();
  const data = base64Image.split(',')[1];

  let fullPrompt = `Here is a photo of a person currently wearing ${currentOutfitDesc}. 
  I want to virtually change their outfit. ${stylePrompt}. 
  Keep the person's face, hair, body shape, and the background environment exactly as they are in the original photo. 
  Only replace the clothing. Make it look as realistic as possible.`;

  if (blurBackground) {
    fullPrompt += ` Additionally, apply a professional cinematic bokeh effect to the background. The background should be softly blurred (shallow depth-of-field), ensuring the person and their new outfit are in sharp, crisp focus and stand out from the environment.`;
  }

  const response: GenerateContentResponse = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            mimeType: 'image/png',
            data: data,
          },
        },
        {
          text: fullPrompt
        }
      ]
    }
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image was generated by the model.");
};

/**
 * Generates a cinematic video from the transformed outfit using Veo 3.1.
 */
export const generateVideoFromOutfit = async (
  base64Image: string,
  styleName: string
): Promise<string> => {
  // Always create a fresh client to ensure the latest API key is used
  const ai = getAIClient(process.env.API_KEY);
  const data = base64Image.split(',')[1];

  let operation = await ai.models.generateVideos({
    model: 'veo-3.1-fast-generate-preview',
    prompt: `A high-fashion cinematic portrait of a person wearing ${styleName} clothing. They are modeling the outfit, subtle movement, high-end production lighting, 4k, professional photography.`,
    image: {
      imageBytes: data,
      mimeType: 'image/png',
    },
    config: {
      numberOfVideos: 1,
      resolution: '720p',
      aspectRatio: '9:16'
    }
  });

  while (!operation.done) {
    await new Promise(resolve => setTimeout(resolve, 8000));
    operation = await ai.operations.getVideosOperation({ operation: operation });
  }

  const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
  if (!downloadLink) throw new Error("Video generation failed.");

  const videoResponse = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
  const blob = await videoResponse.blob();
  return URL.createObjectURL(blob);
};
